#!/bin/bash

set -o errexit

export SBT_OPTS="-Dspecs2.color=false -Dsbt.log.format=true -Dsbt.log.noformat=true \
  -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=3128 -Dtest.port=9003 $SBT_OPTS"

sbt clean test accept dist publish

rm -rf target/*.rpm
./rpm-build/jenkins_job_make_rpm
